version: "3.8"
services:
  backend_bcrypttest:
    
    container_name: bcrypt_test
    image: francescoxx/nsp-template:0.0.2
    
    build:
      context: ./app

    ports:
      - "5000:5000"

    environment:
      - NODE_ENV=production
      - PORT=5000

    volumes:
      - ./app/:/usr/src/app # named volume
      - /usr/src/app/node_modules # anon volume for node_modules

