version: "3.8"
services:
  nsp_backend:
    container_name: nsp_backend
    image: francescoxx/nsp-template:0.0.2
    build:
      context: ./app
    ports:
      - "5000:5000"

    environment:
      - NODE_ENV=production
      - PORT=5000
      - PGUSER=francesco
      - PGPASSWORD=12345
      - PGDATABASE=nsp_database
      - PGHOST=nsp_db # NAME OF THE SERVICE

    depends_on:
      - nsp_db
    volumes:
      - ./app/:/usr/src/app

  nsp_db:
    container_name: nsp_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=nsp_database
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}